### ISSUE TITLE
As a developer I want to know what to do to run the tests automatically on CI

### ISSUE THREAD

**Issue by schmidsi** [LimeChain/matchstick#127]
A very cool pattern is to run tests on CI and automatically deploy the subgraph. Check this example: https://github.com/ETHPoster/subgraph/pull/1/files

What would be the steps to enable matchstick on CI? I imagine it's quite tricky due to the fact that it needs to have the compiled matchstick binary?

Some documentation how to do this would be appreciated.

**Comment by axiomatic-aardvark** [comment]
Hey @schmidsi, thanks for the Issue! We acknowledge this is a very important feature. I'm sure it'll be possible to do even with the current version of Matchstick, but it will be cumbersome and will require jumping through a lot of hoops. 

I think after we integrate Matchstick in `graph-cli` and fix the issue with the deployment failing because of the `runTests` import in the mapping files it'll be a breeze to add a CI step with the tests.

So just to wrap up - right now there are two blockers for effectively using Matchstick in CI - https://github.com/LimeChain/matchstick/issues/107 & https://github.com/LimeChain/matchstick/issues/102. After those are done, we'll add an example CI script to the docs.
