### ISSUE TITLE
Improve logging/error abstractions

### ISSUE THREAD

**Issue by axiomatic-aardvark** [LimeChain/matchstick#191]

**Comment by bsamuels453** [comment]
hey @axiomatic-aardvark, is this ticket for logging/error abstractions when running tests?

I've had a lot of issues writing tests because failed tests don't include stack traces; would that fall under this issue or should I open a ticket?

**Comment by VIVelev** [comment]
Hey @bsamuels453, the feature you are asking about is actually done and it looks likes this:
![](https://user-images.githubusercontent.com/22171622/139104109-47ed8f6c-6f9f-4399-8a27-d5c6f98c850b.png)*

It's just only in the `main` branch. It is not released yet. So, if you really need that feature now, simply build the matchstick binary from `main`! Otherwise, we are probably going to make a new release soon.

**Comment by bsamuels453** [comment]
Thanks, appreciate it
