### ISSUE TITLE
Matchstick is not a unit-testing framework

### ISSUE THREAD

**Issue by juliankrispel** [LimeChain/matchstick#220]
I think calling matchstick a unit-testing framework is confusing, since it is clearly more a tool for system/integration testing. [Unit-testing according wikipedia](https://en.wikipedia.org/wiki/Unit_testing) (as well as in my own experience): "In procedural programming, a unit could be an entire module, but it is more commonly an individual function or procedure".

How about calling it an "integrated test environment" or something of the likes.

I know it's just words, but they do matter and I won't be the last one that's utterly confused by this nomenclature 🙏 

That all being said I appreciate the time and effort that's gone into matchstick, big fan :+1:

**Comment by axiomatic-aardvark** [comment]
Matchstick is a general subgraph testing framework, and is intended to be used mainly for testing a single handler function (which is _the_ unit in subgraph development) in isolation. Of course testing multiple handlers and scenarios is even better and that bloats the tests a lot, but still the focus of testing are the handler functions. That's why in my opinion Matchstick should be considered mainly a unit testing framework with added caveats and features for more extensive testing on top of that.
