### ISSUE TITLE
Display full path of each failed test at the bottom of the output log

### ISSUE THREAD

**Issue by dimitrovmaksim** [LimeChain/matchstick#237]
Try to find a better solution to accumulate and display the full path for each failed test, something like in the screenshot below:
<img width="529" alt="Screenshot 2021-12-01 at 10 27 06" src="https://user-images.githubusercontent.com/20456492/144624465-50a6942d-2101-4503-99ff-2ba9bf53e318.png">
 
The solution I came up with initially [here](https://gist.github.com/dimitrovmaksim/4df0c27189c3663b14390dae995b9198) is not reliable enough and does not handle some cases, which is a problem.

Research Estimate: 2-3 days
We can provide After research is finished

**Comment by dimitrovmaksim** [comment]
I probably should have noticed this earlier, but the last line of the backtrace gives us the file path and the id(?) of the `test()` functions that are failing:
`1: 0x2806 - <unknown>!start:tests/gravity/gravity.test~anonymous|5` 

The `5` at the end is the id of the function, which means it's the 6th test() function in the test file `tests/gravity/gravity.test.ts` (they are counted from 0). Maybe this can be used to fetch the line from the file and we already have the file path from the backtrace.

**Comment by VIVelev** [comment]
I like that idea! You are right about the id.

**Comment by dimitrovmaksim** [comment]
Unfortunately this means a lot of text/string manipulation

**Comment by VIVelev** [comment]
Well, given that AS provides this information in the backtrace, it begs the question if this info could be get programmatically using some kind of an API exposed by the AS compiler.

Nevertheless, even if the raw backtrace has to be processed as a string, I believe it will be easier to implement and more robust, since it is expected that the backtrace is consistent in formatting. Even so, using a "Compiler API" will still be better.

**Comment by dimitrovmaksim** [comment]
Closing for now
