### ISSUE TITLE
Error fetching release: Request failed with status code 404

### ISSUE THREAD

**Issue by stevedefazio** [LimeChain/matchstick#357]
Downloading release from https://github.com/LimeChain/matchstick/releases/download/0.5.1/binary-windows

This gives a 404 error, and looking at the releases, I can see there is indeed no "binary-windows" file. Is this intentional? How do you recommend I run this on windows?

Here is the full error when I run npm run test

> dashboard@1.0.0 test
> graph test

Downloading release from https://github.com/LimeChain/matchstick/releases/download/0.5.1/binary-windows
Error fetching release: Request failed with status code 404
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: dashboard@1.0.0
npm ERR!   at location: C:\Users\Family\projects\subgraph-monorepo\subgraphs\internal-dashboard

**Comment by dimitrovmaksim** [comment]
We removed the windows support some versions ago, because there were some issues with them. You can use WSL (Windows Subsystem for Linux) 
https://docs.microsoft.com/en-us/windows/wsl/install

https://thegraph.com/docs/en/developer/matchstick/#wsl-windows-subsystem-for-linux

 or Docker 
https://thegraph.com/docs/en/developer/matchstick/#docker
